#!/usr/bin/env bash

set -x
set -e

# Run cmake
cmake \
  -DSWIG_EXECUTABLE=/usr/bin/swig \
  -DBUILDDOC=$BUILDDOC \
  -DBUILDCPP=$BUILDCPP \
  -DBUILDFTI=$BUILDFTI \
  -DBUILDSWIGPYTHON=$BUILDSWIGPYTHON \
  -DBUILDSWIGNODE=$BUILDSWIGNODE \
  -DBUILDSWIGJAVA=$BUILDSWIGJAVA \
  -DBUILDCORDOVA=$BUILDCORDOVA \
  -DBUILDEXAMPLES=$BUILDEXAMPLES \
  -DIPK=$IPK \
  -DRPM=$RPM \
  -DNPM=$NPM \
  -DBUILDTESTS=$BUILDTESTS \
  -DWERROR=$WERROR \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
  -H. \
  -Bbuild
